version: '3.1'
services:
  db:
    image: "postgres:14-alpine"
    container_name: "primesynth_service"
    ports:
      - "5432:5432"
    restart: "always"
    environment:
      POSTGRES_DB: "primesynth"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "primesynth"
